useGroupedVersion: true

version_info_list_mobile:
  - value: latest version
  - value: 4.x
    child:
      - 4.0.2
      - 4.0.1
      - 4.0.0
  - value: 3.x
    child:
      - 3.0.3
      - 3.0.2
      - 3.0.1
      - 3.0.0
  - value: 2.x
    child:
      - 2.3.21_ios
      - 2.3.20
      - 2.3.12
      - 2.3.11
      - 2.3.10
      - 2.3.5
      - 2.3.4
      - 2.3.3
      - 2.3.2
      - 2.3.1_ios
      - 2.3.0
      - 2.1.4
      - 2.1.3
      - 2.1.1
      - 2.0.0
