# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu
          [ -d DCEDocMobile ] && rm -rf DCEDocMobile
          [ -d camera-enhancer-docs-mobile ] && rm -rf camera-enhancer-docs-mobile 
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          cd /home/ubuntu

      - name: Build the full site - main
        run: |
          cd /home/ubuntu
          mkdir -p DCEDocMobile
          git clone --depth 1 https://github.com/dynamsoft-docs/camera-enhancer-docs-mobile.git camera-enhancer-docs-mobile
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./camera-enhancer-docs-mobile/* ./DCEDocMobile/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDocMobile/
          cd DCEDocMobile && bundle exec jekyll build
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCEDocMobile/_site/ ./www.dynamsoft.com/camera-enhancer/docs/mobile/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DCEDocMobile-preview ] && rm -rf DCEDocMobile-preview
          [ -d camera-enhancer-docs-mobile-preview ] && rm -rf camera-enhancer-docs-mobile-preview 
          [ -d Docs-Template-Repo-Preview-DCV2 ] && rm -rf Docs-Template-Repo-Preview-DCV2
          cd /home/ubuntu

      - name: Build the full site - preview
        run: |
          cd /home/ubuntu
          mkdir -p DCEDocMobile-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/camera-enhancer-docs-mobile.git camera-enhancer-docs-mobile-preview
          git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cp -rfp ./camera-enhancer-docs-mobile-preview/* ./DCEDocMobile-preview/
          cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCEDocMobile-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocMobile-preview/_config.yml
          cd DCEDocMobile-preview && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCEDocPreview/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/mobile/

          
