# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      # old (04-27-2023 back up)
      # - name: Run a multi-line script
      #   run: |
      #     cd /home/ubuntu
      #     [ -d camera-enhancer-docs ] && rm -rf camera-enhancer-docs
      #     [ ! -d DCEDoc ] && mkdir -p DCEDoc
      #     [ ! -d camera-enhancer-docs ] && git clone --depth 1 https://github.com/Dynamsoft/camera-enhancer-docs.git camera-enhancer-docs
      #     [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
      #     cd camera-enhancer-docs && git pull && cd .. && cp -rfp ./camera-enhancer-docs/* ./DCEDoc/
      #     cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDoc/
      #     cd DCEDoc && bundle exec jekyll build --incremental
      #     python3 /home/ubuntu/ftp.py /home/ubuntu/DCEDoc/_site/ ./www.dynamsoft.com/camera-enhancer/docs/ prod
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocMobile ] && mkdir -p DCEDocMobile
          [ ! -d camera-enhancer-docs-mobile ] && git clone --depth 1 https://github.com/dynamsoft-docs/camera-enhancer-docs-mobile.git camera-enhancer-docs-mobile
          [ ! -d Docs-Template-Repo-Preview-DCV2 ] && git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cd camera-enhancer-docs-mobile && git pull && cd .. && cp -rfp ./camera-enhancer-docs-mobile/* ./DCEDocMobile/
          cd Docs-Template-Repo-Preview-DCV2 && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCEDocMobile/
          cd DCEDocMobile && bundle exec jekyll build --incremental
          python3 /home/ubuntu/ftp.py /home/ubuntu/DCEDocMobile/_site/ ./www.dynamsoft.com/camera-enhancer/docs/mobile/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCEDocMobile-preview ] && mkdir -p DCEDocMobile-preview
          [ ! -d camera-enhancer-docs-mobile-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/camera-enhancer-docs-mobile.git camera-enhancer-docs-mobile-preview
          [ ! -d Docs-Template-Repo-Preview-DCV2 ] && git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cd camera-enhancer-docs-mobile-preview && git pull && cd .. && cp -rfp ./camera-enhancer-docs-mobile-preview/* ./DCEDocMobile-preview/
          cd Docs-Template-Repo-Preview-DCV2 && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCEDocMobile-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocMobile-preview/_config.yml
          cd DCEDocMobile-preview && bundle exec jekyll build --incremental && cd ..

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCEDocMobile-preview/_site/
          server-dir: /www.dynamsoft.com/camera-enhancer/docs/mobile/
    # old (04/27/2023 back up)
    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    #   # Runs a set of commands using the runners shell
    #   - name: clear space
    #     run: |
    #       cd /home/ubuntu 
    #       [ -d DCEDocPreview ] && rm -rf DCEDocPreview
    #       [ -d camera-enhancer-docs-preview ] && rm -rf camera-enhancer-docs-preview
    #       [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
    #       cd /home/ubuntu

    #   - name: Build the site
    #     run: |
    #       cd /home/ubuntu
    #       [ ! -d DCEDocPreview ] && mkdir -p DCEDocPreview
    #       [ ! -d camera-enhancer-docs-preview ] && git clone --depth 1 --branch preview https://github.com/Dynamsoft/camera-enhancer-docs.git camera-enhancer-docs-preview
    #       [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
    #       cd camera-enhancer-docs-preview && git pull && cd .. && cp -rfp ./camera-enhancer-docs-preview/* ./DCEDocPreview/
    #       cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DCEDocPreview/
    #       sed -i -e "1,3s/blob\/master$/blob\/preview/" \
    #       -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCEDocPreview/_config.yml
    #       cd DCEDocPreview && bundle exec jekyll build --incremental

    #   - name: Sync files
    #     uses: SamKirkland/FTP-Deploy-Action@4.3.0
    #     with:
    #       server: ${{ secrets.FTP_TEST_SITE_SERVER }}
    #       username: ${{ secrets.FTP_TEST_SITE_USER }}
    #       password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
    #       port: 7500 
    #       local-dir: /home/ubuntu/DCEDocPreview/_site/
    #       server-dir: /www.dynamsoft.com/camera-enhancer/docs/

          
